<!-- Generated by Trae Work -->
<template>
  <svg
    :viewBox="`0 0 ${size} ${size}`"
    :width="size"
    :height="size"
    :stroke="color"
    stroke-width="2"
    fill="none"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="share-icon"
  >
    <!-- 微信：双气泡轮廓 -->
    <g v-if="type === 'wechat'">
      <path d="M22 14c0 4.4-4 8-9 8-1.3 0-2.6-.3-3.7-.8L8 23l1.8-2.2C7.1 19.3 5 16.9 5 14c0-4.4 4-8 9-8s9 3.6 9 8z"/>
      <path d="M13 13h.01M19 13h.01"/>
      <path d="M33 20c0 3.3-3.1 6-7 6-.9 0-1.8-.2-2.6-.5L22 28l1.2-1.6c-2.5-.9-4.2-3-4.2-5.4 0-3.3 3.1-6 7-6s7 2.7 7 6z"/>
      <path d="M25 19h.01M30 19h.01"/>
    </g>

    <!-- 朋友圈：圆形相框 + 小人 -->
    <g v-else-if="type === 'moments'">
      <circle cx="24" cy="24" r="18"/>
      <circle cx="24" cy="20" r="5"/>
      <path d="M13 36c1.5-4.5 5-7 11-7s9.5 2.5 11 7"/>
      <path d="M17 14l3-3 4 4"/>
    </g>

    <!-- QQ：企鹅简笔轮廓 -->
    <g v-else-if="type === 'qq'">
      <ellipse cx="24" cy="26" rx="11" ry="13"/>
      <ellipse cx="24" cy="16" rx="9" ry="8"/>
      <circle cx="20.5" cy="15" r="1.5" fill="currentColor" stroke="none"/>
      <circle cx="27.5" cy="15" r="1.5" fill="currentColor" stroke="none"/>
      <path d="M22 19c.8 1 2.4 1.5 3.5 1M19 27l-3-2M29 27l3-2"/>
      <path d="M18 37l-2 5M30 37l2 5"/>
      <path d="M21 32v5M27 32v5"/>
    </g>

    <!-- 系统/更多：齿轮 -->
    <g v-else-if="type === 'system'">
      <circle cx="24" cy="24" r="7"/>
      <path d="M24 6v4M24 38v-4M6 24h4M38 24h-4M11 11l3 3M37 37l-3-3M11 37l3-3M37 11l-3 3"/>
    </g>

    <!-- 手机：圆角矩形 + 顶部听筒 -->
    <g v-else-if="type === 'phone'">
      <rect x="14" y="5" width="20" height="38" rx="4"/>
      <line x1="20" y1="9" x2="28" y2="9"/>
      <circle cx="24" cy="37" r="1.5" fill="currentColor" stroke="none"/>
    </g>
  </svg>
</template>

<script setup lang="ts">
defineProps<{
  type: 'wechat' | 'moments' | 'qq' | 'system' | 'phone'
  size?: number
  color?: string
}>()
</script>

<style scoped>
.share-icon {
  display: block;
  flex-shrink: 0;
}
</style>
